### ISSUE TITLE
State changes only reaching members listed in "hostsToJoin"

### ISSUE THREAD

**Issue by nomilous** [mrhooray/swim-js#10]
Given cluster [0,1,2,3,...,n] where [0,1,2] are configured on all members as the "hostsToJoin" for bootsrapping.

When stopping member n the states 1 and/or 2 notification reliably reaches all other members (as expected).

When resuming member n the new state 0 notification consistently only ever reaches members [0,1,2] - the "hostsToJoin" list.

Any further state changes from member n only reach members [0,1,2].

It would therefore appear that either the entire cluster needs to be included in the hosts to join list or we're doing something wrong.

Your guidance would be much appreciated.

test: https://github.com/happner/membership-tests/blob/master/tests/swim.js

**Comment by nomilous** [comment]
I see now. The `incarnation` needs to be incremented _externally_ across a member restart.

**Comment by nomilous** [comment]
The spec isn't clear on whether or not restarting members should resume from previous incarnation. But that seems to be the only thing that makes this work reliably.

Perhaps important enough to update the readme. See pull request.

**Comment by mrhooray** [comment]
@nomilous when joining cluster, each node from `hostsToJoin` list would bring joining node's incarnation up to date by sending its view of the membership back to joining node for resolution

currently faulty nodes are not sent back to joining node and #13 addresses that, could you try to see whether `sync` branch fixes the issue you observed?

also gonna close #11 since it has many unrelated changes

**Comment by nomilous** [comment]
@mrhooray 

FYI

I've made the faulty-list live on indefinitely through the cluster by reloading it on sync into the joining member.

https://github.com/happner/swim-js/pull/4

Not pushing because I've also removed farmhash and msgpack.
