### ISSUE TITLE
Resuming member's starting meta gets overwritten.

### ISSUE THREAD

**Issue by nomilous** [mrhooray/swim-js#14]
The resuming member's starting meta gets overwritten from the failed-list as synced back when joining. The resuming member record is then disseminated with its previous meta making it impossible to rejoin with changed meta.

https://github.com/mrhooray/swim-js/blob/master/lib/member.js#L27

**Comment by mrhooray** [comment]
It was a conscious choice but I don't have a strong opinion on it.

Wonder what's your use case/what do you store in meta? We can change it if it makes more sense.

**Comment by dcharbonnier** [comment]
My personal use case is a "weight" associated to the member and I don't want to introduce a complexity to disseminate such small information (not updated frequently) in the cluster.

**Comment by mrhooray** [comment]
@dcharbonnier the change in your PR regarding meta didn't change the behavior

> recovered node will have meta overwritten by previous state in the cluster

which is the opposite of what @nomilous wants. Is this want you want?

**Comment by dcharbonnier** [comment]
I don't think @mrhooray the problem of @nomilous is that the metadata are not updated when it re-join and so he get the previous ones, 0076685 allow any king of update, can you explain why this was nto the case ?

**Comment by mrhooray** [comment]
@dcharbonnier 
> the metadata are not updated when it re-join and so he get the previous ones
this is not what's happening on node re-join the cluster

For example, when a node re-joins the cluster after restart, its local incarnation number would be 0 and local metadata could be something new

- it'll try to sync with other seed nodes in the cluster and receive its previous state in the cluster including previous metadata
- [this logic](https://github.com/mrhooray/swim-js/blob/master/lib/member.js#L27-L30) would allow it catch up on incarnation number and have local metadata **updated/overridden** to previous state

Like I mentioned earlier, it's a design choice for some use cases but may not fit for others. If we don't want new metadata to be overridden, we could simply remove the logic around updating local metadata.

It would make sense to expose an option to let use cases decide which behavior to use. Also make not having local metadata overridden the default behavior since it probably fits most use cases.

Dose above addresses your question and make sense to you? I'll find some time soon to implement this unless you prefer updating the existing PR.

**Comment by mrhooray** [comment]
resolved by 08f284648afbd077387378a83691e23df6f05735
